name: Deploy Lambda through Cloudformatin
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Delete Caches
        run: |
          sudo rm /var/lib/apt/lists/lock
          sudo rm /var/cache/apt/archives/lock
          sudo rm /var/lib/dpkg/lock*

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get install -y unzip curl

      - name: Install aws-cli
        uses: hannut91/aws-cli@1.18.43
        with:
          args: --version

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "10"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACTIONS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACTIONS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Set System Locale
        run: export LANG=C.utf8

      - name: Build & Packaging & Deploy
        run: |
          cd /home/runner/work/delivery-tracker/delivery-tracker/packages/apiserver/
          rm -rf dist
          rm -rf node_modules
          npm run setup
